import tempfile
import unittest
import json
from pathlib import Path
from unittest.mock import patch

from tools.enforcement_kernel import EnforcementKernel, KernelRequest, TransitionError


class FakeModelClient:
    provider = "openai"

    def generate(self, model: str, prompt: str) -> str:
        return f"{model}: {prompt.upper()}"


class FailingModelClient:
    provider = "local_model_draft"

    def generate(self, model: str, prompt: str) -> str:
        raise RuntimeError("model service unavailable")


class FakeHTTPResponse:
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc, traceback):
        return False

    def read(self) -> bytes:
        return json.dumps({"output_text": "local compatible response"}).encode("utf-8")


class ModelAdapterTests(unittest.TestCase):
    def test_model_adapter_writes_draft_artifact_through_local_filesystem(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            kernel = EnforcementKernel(root)
            run = kernel.start(
                KernelRequest(
                    request_id="req-model-draft",
                    title="Model draft",
                    actor_id="actor-operator",
                    requested_outcome="Draft a local artifact with a model.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=False,
                    required_workstreams=["research"],
                )
            )
            kernel.dispatch_ready(run.run_id)

            completed = kernel.draft_model_artifact(
                run.run_id,
                "research",
                "drafts/research.md",
                prompt="summarize request",
                model="gpt-test",
                actor_id="actor-research",
                model_client=FakeModelClient(),
            )

            artifact = completed.artifacts[-1]
            artifact_path = root / artifact.path
            self.assertEqual(artifact.content, "gpt-test: SUMMARIZE REQUEST")
            self.assertEqual(artifact_path.read_text(encoding="utf-8"), "gpt-test: SUMMARIZE REQUEST")
            self.assertIn("SUPPORTED::Model draft generated by openai/gpt-test.", artifact.claims)
            self.assertEqual(len(completed.model_call_records), 1)
            model_call = completed.model_call_records[0]
            self.assertEqual(model_call.provider, "openai")
            self.assertEqual(model_call.model, "gpt-test")
            self.assertEqual(model_call.actor_id, "actor-research")
            self.assertEqual(model_call.workstream_id, "research")
            self.assertEqual(model_call.result, "success")
            self.assertEqual(model_call.output_hash, artifact.content_hash)
            self.assertEqual(model_call.artifact_id, artifact.artifact_id)
            self.assertTrue(model_call.prompt_hash.startswith("sha256:"))

    def test_model_adapter_records_failure_packet_when_generation_fails(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            kernel = EnforcementKernel(root)
            run = kernel.start(
                KernelRequest(
                    request_id="req-model-failure",
                    title="Model failure",
                    actor_id="actor-operator",
                    requested_outcome="Capture model failure evidence.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=False,
                    required_workstreams=["research"],
                )
            )
            kernel.dispatch_ready(run.run_id)

            with self.assertRaisesRegex(TransitionError, "model service unavailable"):
                kernel.draft_model_artifact(
                    run.run_id,
                    "research",
                    "drafts/research.md",
                    prompt="summarize request",
                    model="local-draft-v1",
                    actor_id="actor-research",
                    model_client=FailingModelClient(),
                )

            failed = kernel.store.load(run.run_id)
            self.assertEqual(len(failed.failure_packets), 1)
            failure = failed.failure_packets[0]
            self.assertEqual(failure.workstream_id, "research")
            self.assertEqual(failure.actor_id, "actor-research")
            self.assertEqual(failure.error_type, "model_adapter_error")
            self.assertEqual(failure.error_message, "model service unavailable")
            self.assertFalse(failure.retryable)
            self.assertEqual(failure.resolution, "blocked")
            self.assertEqual(len(failed.model_call_records), 1)
            model_call = failed.model_call_records[0]
            self.assertEqual(model_call.provider, "local_model_draft")
            self.assertEqual(model_call.model, "local-draft-v1")
            self.assertEqual(model_call.result, "failure")
            self.assertIsNone(model_call.output_hash)
            self.assertIsNone(model_call.artifact_id)
            self.assertTrue(model_call.prompt_hash.startswith("sha256:"))

    def test_model_adapter_blocks_sensitive_or_external_runs(self):
        with tempfile.TemporaryDirectory() as tmp:
            kernel = EnforcementKernel(Path(tmp))
            run = kernel.start(
                KernelRequest(
                    request_id="req-model-sensitive",
                    title="Sensitive model draft",
                    actor_id="actor-operator",
                    requested_outcome="Draft using sensitive data.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=True,
                    required_workstreams=["research"],
                )
            )

            with self.assertRaisesRegex(TransitionError, "Model adapter requires non-sensitive internal work"):
                kernel.draft_model_artifact(
                    run.run_id,
                    "research",
                    "drafts/research.md",
                    prompt="summarize sensitive request",
                    model="gpt-test",
                    actor_id="actor-research",
                    model_client=FakeModelClient(),
                )

    def test_openai_model_adapter_is_disabled_without_config(self):
        with tempfile.TemporaryDirectory() as tmp:
            kernel = EnforcementKernel(Path(tmp))
            run = kernel.start(
                KernelRequest(
                    request_id="req-openai-disabled",
                    title="OpenAI disabled",
                    actor_id="actor-operator",
                    requested_outcome="Try OpenAI without config.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=False,
                    required_workstreams=["research"],
                )
            )
            kernel.dispatch_ready(run.run_id)

            with self.assertRaisesRegex(TransitionError, "Model provider openai is not enabled"):
                kernel.draft_model_artifact(
                    run.run_id,
                    "research",
                    "drafts/research.md",
                    prompt="summarize request",
                    model="gpt-5.6-luna",
                    actor_id="actor-research",
                    provider="openai",
                )

    def test_openai_model_adapter_requires_allowed_model_and_api_key_env(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            config_path = root / ".agencyos-runtime" / "config.local.json"
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(
                json.dumps(
                    {
                        "model_adapters": {
                            "openai": {
                                "enabled": True,
                                "api_key_env": "OPENAI_API_KEY",
                                "allowed_models": ["gpt-5.6-luna"],
                                "max_prompt_chars": 100,
                                "max_output_chars": 1000,
                            }
                        }
                    }
                ),
                encoding="utf-8",
            )
            kernel = EnforcementKernel(root)
            run = kernel.start(
                KernelRequest(
                    request_id="req-openai-policy",
                    title="OpenAI policy",
                    actor_id="actor-operator",
                    requested_outcome="Try OpenAI with config.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=False,
                    required_workstreams=["research"],
                )
            )
            kernel.dispatch_ready(run.run_id)

            with self.assertRaisesRegex(TransitionError, "Model gpt-other is not allowed"):
                kernel.draft_model_artifact(
                    run.run_id,
                    "research",
                    "drafts/research.md",
                    prompt="summarize request",
                    model="gpt-other",
                    actor_id="actor-research",
                    provider="openai",
                )

            with patch.dict("os.environ", {}, clear=True):
                with self.assertRaisesRegex(TransitionError, "OPENAI_API_KEY is not configured"):
                    kernel.draft_model_artifact(
                        run.run_id,
                        "research",
                        "drafts/research.md",
                        prompt="summarize request",
                        model="gpt-5.6-luna",
                        actor_id="actor-research",
                        provider="openai",
                    )

    def test_openai_compatible_local_provider_uses_base_url_without_api_key(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            config_path = root / ".agencyos-runtime" / "config.local.json"
            config_path.parent.mkdir(parents=True, exist_ok=True)
            config_path.write_text(
                json.dumps(
                    {
                        "model_adapters": {
                            "openai_compatible_local": {
                                "enabled": True,
                                "base_url": "http://localhost:1234/v1",
                                "api_key_env": "",
                                "allowed_models": ["*"],
                                "max_prompt_chars": 100,
                                "max_output_chars": 1000,
                            }
                        }
                    }
                ),
                encoding="utf-8",
            )
            kernel = EnforcementKernel(root)
            run = kernel.start(
                KernelRequest(
                    request_id="req-compatible-local",
                    title="OpenAI compatible local",
                    actor_id="actor-operator",
                    requested_outcome="Draft with a local OpenAI-compatible server.",
                    action_class="internal_artifact",
                    reversible=True,
                    external=False,
                    sensitive=False,
                    required_workstreams=["research"],
                )
            )
            kernel.dispatch_ready(run.run_id)

            captured = {}

            def fake_urlopen(request, timeout):
                captured["url"] = request.full_url
                captured["authorization"] = request.headers.get("Authorization")
                captured["body"] = json.loads(request.data.decode("utf-8"))
                return FakeHTTPResponse()

            with patch("urllib.request.urlopen", side_effect=fake_urlopen):
                completed = kernel.draft_model_artifact(
                    run.run_id,
                    "research",
                    "drafts/research.md",
                    prompt="summarize request",
                    model="active",
                    actor_id="actor-research",
                    provider="openai_compatible_local",
                )

            self.assertEqual(captured["url"], "http://localhost:1234/v1/responses")
            self.assertIsNone(captured["authorization"])
            self.assertEqual(captured["body"]["model"], "active")
            artifact = completed.artifacts[-1]
            self.assertEqual(artifact.content, "local compatible response")
            self.assertIn("SUPPORTED::Model draft generated by openai_compatible_local/active.", artifact.claims)
            model_call = completed.model_call_records[0]
            self.assertEqual(model_call.provider, "openai_compatible_local")
            self.assertEqual(model_call.model, "active")
            self.assertEqual(model_call.result, "success")


if __name__ == "__main__":
    unittest.main()
